2022-06-06 00:12:46,561 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: local variable 'write' referenced before assignment
2022-06-06 00:13:06,476 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: local variable 'write' referenced before assignment
2022-06-06 00:16:48,343 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/base.py> <handler.handle_request()>: 'NoneType' object is not iterable
2022-06-06 00:18:29,252 ERROR: <client.py> <result = self.send_request(request.json(exclude_none=True, ensure_ascii=False).encode(DEFAULT_ENCODING))>: [Errno 32] Broken pipe
2022-06-06 00:21:20,735 ERROR: <client.py> <client.request(Action.quit)>: Not connected
2022-06-06 00:21:30,726 ERROR: <client.py> <client.request(Action.quit)>: Not connected
2022-06-06 00:22:28,900 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 00:22:28,901 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 14:49:23,882 ERROR: <client.py> <result = self.send_request(request.json(exclude_none=True, ensure_ascii=False).encode(DEFAULT_ENCODING))>: [Errno 9] Bad file descriptor
2022-06-06 14:49:31,058 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 14:49:31,058 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 14:53:19,013 ERROR: <client.py> <handler()>: __enter__
2022-06-06 14:53:19,014 ERROR: <client.py> <handler()>: __enter__
2022-06-06 14:54:08,909 ERROR: <client.py> <handler()>: __enter__
2022-06-06 14:54:08,909 ERROR: <client.py> <handler()>: __enter__
2022-06-06 14:54:10,843 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 14:54:10,843 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 14:57:16,225 ERROR: <client.py> <handler()>: __enter__
2022-06-06 14:57:16,225 ERROR: <client.py> <handler()>: __enter__
2022-06-06 14:57:28,087 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 14:57:28,087 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:14:46,153 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:14:46,153 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:14:49,471 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:14:49,471 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:17:16,461 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:17:16,461 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:17:22,540 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:17:22,540 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:20:30,113 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:20:30,114 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:20:37,527 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:20:37,527 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:21:39,181 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:21:39,182 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:21:40,774 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:21:40,774 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:22:08,119 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:22:08,119 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:22:11,741 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:22:11,741 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:24:33,292 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:24:33,292 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:24:39,354 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:24:39,354 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:29:56,988 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:29:56,989 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:30:06,938 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:30:06,939 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:30:29,418 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:30:29,418 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:30:41,170 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:30:41,170 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:36:35,051 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:36:35,051 ERROR: <client.py> <handler()>: __enter__
2022-06-06 15:36:37,778 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:36:37,778 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:37:55,186 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: __enter__
2022-06-06 15:37:55,186 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: __enter__
2022-06-06 15:37:58,416 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:37:58,416 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:38:54,664 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: __enter__
2022-06-06 15:38:54,665 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: __enter__
2022-06-06 15:40:46,523 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: __enter__
2022-06-06 15:40:46,523 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: __enter__
2022-06-06 15:44:13,215 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
2022-06-06 15:44:13,215 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <server.serve()>: file descriptor cannot be a negative integer (-1)
2022-06-06 15:47:11,364 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/base.py> <handler.handle_request()>: 'NoneType' object has no attribute 'sock'
2022-06-06 15:47:22,828 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: [Errno 9] Bad file descriptor
2022-06-06 15:50:59,341 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: [Errno 9] Bad file descriptor
2022-06-06 15:51:03,725 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: [Errno 9] Bad file descriptor
2022-06-06 15:53:03,081 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: [Errno 9] Bad file descriptor
2022-06-06 15:53:06,457 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: [Errno 9] Bad file descriptor
2022-06-06 16:05:51,602 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: [Errno 9] Bad file descriptor
2022-06-06 16:05:54,012 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: [Errno 9] Bad file descriptor
2022-06-06 22:50:52,804 ERROR: <client.py> <client.run()>: 
2022-06-06 22:51:42,531 ERROR: </usr/lib/python3.8/threading.py> <self._target(*self._args, **self._kwargs)>: [Errno 9] Bad file descriptor
2022-06-06 22:51:42,532 ERROR: </home/stanislav/study/client_server_app/client-server-applcations/server.py> <self.close_request()>: 'NoneType' object has no attribute 'user'
